# Generated by Django 3.0.6 on 2020-06-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_art', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(null=True)),
                ('correo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Det_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('cant_compra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Det_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cant_compra', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Articulos')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Det_factura')),
            ],
        ),
        migrations.CreateModel(
            name='Legajo_empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguedad', models.DateField()),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Datos_personales')),
                ('legajo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Legajo_empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Det_venta')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Facturas')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Personas')),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Tipo_persona'),
        ),
        migrations.AddField(
            model_name='det_venta',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Facturas'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Domicilio'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Rubros'),
        ),
    ]
