# Generated by Django 3.0.6 on 2020-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200602_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_venta',
            name='factura',
        ),
        migrations.AddField(
            model_name='det_venta',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
