# Generated by Django 3.0.6 on 2020-06-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200602_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='det_venta',
            old_name='fecha_compra',
            new_name='fecha_venta',
        ),
    ]
