# Generated by Django 3.0.6 on 2020-06-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200602_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='det_venta',
            old_name='cant_compra',
            new_name='cant_venta',
        ),
        migrations.AddField(
            model_name='facturas',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Tipo_persona'),
        ),
        migrations.AlterField(
            model_name='det_venta',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Articulos'),
        ),
    ]
