# Generated by Django 3.0.6 on 2020-06-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200602_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='det_factura',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Tipo_persona'),
        ),
    ]
