# Generated by Django 3.0.6 on 2020-06-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200602_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Rubros'),
        ),
    ]
