# Generated by Django 3.0.6 on 2020-06-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200603_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_venta',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
