# Generated by Django 3.0.6 on 2020-06-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200603_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Rubros'),
        ),
        migrations.AlterField(
            model_name='det_venta',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Articulos'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Articulos'),
        ),
    ]
